"""
auto_tagger.py — FrameForge Auto-Tagger POC.

Two-stage Gemini pipeline that converts a sketch image into a Danbooru tag
string ready for injection into the ComfyUI positive prompt field (node "145").

  Stage 1 (Vision):  sketch image → detailed character/visual description
  Stage 2 (Tags):    description → Danbooru tag string (character + visual only)
  Assembly:          quality_prefix + gemini_tags + scene_direction

The quality prefix and scene direction are never sent to Gemini — they are
concatenated by code in assemble_prompt(). Gemini only handles the character
identity and visual attribute tags, where hallucination risk is lowest.

Tag order follows Animagine XL 3.1 conventions:
  1girl/1boy → character_name → series → visual attributes

No Qt imports. This module must remain UI-agnostic.

Integration point:
    render_worker.py calls analyze_image(), generate_tags(), and assemble_prompt()
    in sequence. auto_tag() is the convenience wrapper used by the CLI.
"""

import os
import time
from pathlib import Path

from dotenv import load_dotenv
from google import genai
from google.genai import types

# ---------------------------------------------------------------------------
# Model configuration
# ---------------------------------------------------------------------------

# Both stages use the same Gemini 2.5 Flash model.
# Stage 1 sends image + text; Stage 2 sends text only.
_VISION_MODEL = "gemini-2.5-flash"
_TAG_MODEL = "gemini-2.5-flash"

# Maximum tokens per stage. Thinking tokens count against this limit on
# Gemini 2.5 Flash, so the budgets are set generously.
_VISION_MAX_TOKENS = 2048
_TAG_MAX_TOKENS = 4096

# ---------------------------------------------------------------------------
# Quality suffix — never generated by Gemini, always appended by code.
# Animagine XL 3.1 tag order: character identity first (highest CLIP weight),
# quality/aesthetic/year/rating boosters last.
# ---------------------------------------------------------------------------

QUALITY_SUFFIX = "masterpiece, best quality, very aesthetic, absurdres, newest, safe"

# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

_VISION_PROMPT = (
    "Describe this sketch for a digital artist. Focus only on what maps to "
    "Danbooru tags. Report:\n\n"
    "- Number of characters and apparent gender (e.g. 'one female character')\n"
    "- Character identification: if you recognize this as a named character from "
    "anime, manga, or games, state their exact name and series\n"
    "- Hair: color, length (short/medium/long/very long), and style "
    "(straight/wavy/curly/spiky/twin_tails/ponytail/braid/etc.)\n"
    "- Eyes: color\n"
    "- Clothing: list each garment and accessory specifically "
    "(e.g. 'white collared shirt, dark pleated skirt, black knee-high socks, "
    "red ribbon at collar')\n"
    "- Body framing: full_body / upper_body / cowboy_shot / portrait / close-up "
    "(cowboy_shot = from waist to head)\n"
    "- Pose and action (e.g. 'standing with arms crossed', 'sitting', 'running')\n"
    "- Facial expression (e.g. 'smiling', 'surprised', 'neutral', 'angry')\n\n"
    "Do NOT describe background elements. "
    "Do NOT describe art style. "
    "Be specific and factual."
)

_TAG_PROMPT_TEMPLATE = """\
Convert the following sketch description into a Danbooru tag string for Animagine XL 3.1.

Output order (follow exactly):
1. Subject count: 1girl / 1boy / 2girls / 1boy_1girl / etc.
2. Character name if recognizable (e.g. monkey_d._luffy) — use the exact Danbooru character tag
3. Series name if recognizable (e.g. one_piece) — or use "original" for original characters
4. Visual tags: hair color, hair length, hair style, eye color, clothing items, accessories, expression, pose, body framing

Rules:
- Use ONLY real Danbooru tags (lowercase, underscored: long_hair, school_uniform, closed_eyes)
- Do NOT use natural language phrases (not "intense eyes" — use glowing_eyes or omit)
- Do NOT include quality tags (no masterpiece, best quality, highres, etc.) — added by code
- Do NOT include background or environment tags (no forest, sunset, sky, ocean) — added separately
- Do NOT include rating tags (no safe, sensitive, nsfw, explicit)
- Do NOT include art style tags (no anime_style, sketch, lineart, illustration)
- Aim for 15–25 tags. Do not pad with vague or redundant tags.
- Output ONLY the comma-separated tag string — no explanation, no "Tags:" prefix, no markdown

Description:
{description}

Tags:"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def analyze_image(image_path: str) -> str:
    """
    Stage 1: send a sketch image to the vision model and return a detailed
    character/visual description.

    Parameters
    ----------
    image_path:
        Absolute or relative path to the sketch (PNG or JPEG).

    Returns
    -------
    str
        Multi-sentence description focused on character attributes and visual
        details that map to Danbooru tags. Suitable for use as Stage 2 input.

    Raises
    ------
    EnvironmentError
        If GEMINI_API_KEY is missing from the environment.
    FileNotFoundError
        If image_path does not point to an existing file.
    google.genai.errors.APIError
        If the Gemini API returns an error.
    """
    client = _get_client()

    print(f"[auto_tagger] Stage 1 — vision model: {_VISION_MODEL}")
    print(f"[auto_tagger] Image: {image_path}")

    suffix = Path(image_path).suffix.lower()
    mime_type = "image/jpeg" if suffix in (".jpg", ".jpeg") else "image/png"

    with open(image_path, "rb") as f:
        image_bytes = f.read()

    response = client.models.generate_content(
        model=_VISION_MODEL,
        contents=[
            _VISION_PROMPT,
            types.Part.from_bytes(data=image_bytes, mime_type=mime_type),
        ],
        config=types.GenerateContentConfig(
            max_output_tokens=_VISION_MAX_TOKENS,
            thinking_config=types.ThinkingConfig(thinking_budget=0),
        ),
    )

    description = response.text.strip() if response.text else ""
    print(f"[auto_tagger] Stage 1 complete — {len(description)} chars")
    return description


def generate_tags(description: str) -> str:
    """
    Stage 2: convert an image description into a Danbooru tag string following
    Animagine XL 3.1 conventions.

    Quality tags and scene direction are NOT part of the output — they are
    handled separately by assemble_prompt(). This function only produces
    character identity and visual attribute tags.

    Parameters
    ----------
    description:
        Detailed character/visual description, typically from analyze_image().

    Returns
    -------
    str
        Comma-separated Danbooru tag string in Animagine XL 3.1 order:
        subject count → character name → series → visual attributes.
        Does not include quality tags or background tags.

    Raises
    ------
    EnvironmentError
        If GEMINI_API_KEY is missing from the environment.
    google.genai.errors.APIError
        If the Gemini API returns an error.
    """
    client = _get_client()

    prompt = _TAG_PROMPT_TEMPLATE.format(description=description)

    print(f"[auto_tagger] Stage 2 — tag model: {_TAG_MODEL}")

    response = client.models.generate_content(
        model=_TAG_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            max_output_tokens=_TAG_MAX_TOKENS,
            thinking_config=types.ThinkingConfig(thinking_budget=0),
        ),
    )

    tags = response.text.strip() if response.text else ""
    # Strip any leading "Tags:" the model might echo back despite instructions.
    if tags.lower().startswith("tags:"):
        tags = tags[5:].strip()

    print(f"[auto_tagger] Stage 2 complete — {len(tags.split(','))} tags")
    return tags


def assemble_prompt(gemini_tags: str, scene_direction: str | None = None) -> str:
    """
    Assemble the final ComfyUI positive prompt from its three components.

    Structure: {gemini_tags}, {scene_direction}, {QUALITY_SUFFIX}

    Character identity tags come first for maximum CLIP attention weight.
    Quality/aesthetic/year/rating boosters are appended last by code — never
    generated by Gemini.

    Parameters
    ----------
    gemini_tags:
        Character identity and visual attribute tags from generate_tags().
        Pass an empty string if auto-tagging failed (fallback path).
    scene_direction:
        Optional raw scene direction text from the user's input field.
        Appended after gemini_tags, before quality suffix.

    Returns
    -------
    str
        The fully assembled prompt ready for injection into workflow node "145".
    """
    parts = []
    if gemini_tags.strip():
        parts.append(gemini_tags.strip())
    if scene_direction and scene_direction.strip():
        parts.append(scene_direction.strip())
    parts.append(QUALITY_SUFFIX)

    final = ", ".join(parts)

    print(f"[auto_tagger] Gemini tags:       {gemini_tags.strip() or '(none)'}")
    print(f"[auto_tagger] Scene direction:   {scene_direction or '(none)'}")
    print(f"[auto_tagger] Quality suffix:    {QUALITY_SUFFIX}")
    print(f"[auto_tagger] Final prompt:      {final}")

    return final


def auto_tag(image_path: str, scene_direction: str | None = None) -> str:
    """
    Convenience wrapper: run Stage 1, Stage 2, and assemble the final prompt.
    Used by the CLI. render_worker.py calls the stages individually for
    granular status signal emission between stages.

    Parameters
    ----------
    image_path:
        Absolute or relative path to the sketch (PNG or JPEG).
    scene_direction:
        Optional natural-language scene context (background, lighting, mood).
        Appended after Gemini's tags without being sent to the model.

    Returns
    -------
    str
        Fully assembled ComfyUI prompt: quality prefix + Gemini tags + scene direction.

    Raises
    ------
    EnvironmentError
        If GEMINI_API_KEY is missing from the environment.
    FileNotFoundError
        If image_path does not point to an existing file.
    google.genai.errors.APIError
        If the Gemini API returns an error at either stage.
    """
    description = analyze_image(image_path)
    gemini_tags = generate_tags(description)
    return assemble_prompt(gemini_tags, scene_direction)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _get_client() -> genai.Client:
    """
    Load .env, verify GEMINI_API_KEY is present, and return a configured
    Gemini client. Called once per public function invocation.
    (load_dotenv is idempotent so repeated calls are safe.)
    """
    load_dotenv()
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise EnvironmentError(
            "GEMINI_API_KEY not found. "
            "Add it to your .env file:  GEMINI_API_KEY=AIza..."
        )
    return genai.Client(api_key=api_key)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="FrameForge Auto-Tagger — sketch → Danbooru tags"
    )
    parser.add_argument("--image", required=True, help="Path to sketch image (PNG or JPEG)")
    parser.add_argument(
        "--prompt",
        default=None,
        help='Optional scene direction, e.g. "sunset, forest background"',
    )
    args = parser.parse_args()

    print("[auto_tagger] Starting two-stage tag pipeline...")
    print()

    print("[auto_tagger] Stage 1: analyzing image...")
    description = analyze_image(args.image)
    print()
    print("=== Description ===")
    print(description)
    print()

    print("[auto_tagger] Stage 2: generating Danbooru tags...")
    tags = generate_tags(description)
    print()
    print("=== Gemini Tags ===")
    print(tags)
    print()

    print("[auto_tagger] Assembling final prompt...")
    final = assemble_prompt(tags, args.prompt)
    print()
    print("=== Final Prompt ===")
    print(final)
